export const iastTestCases = [
  // Words with 'ik' vowels - should return true for isIkVowel
  { word: 'iti', expected: true, vowel: 'i' },
  { word: 'īśa', expected: true, vowel: 'ī' },
  { word: 'upakaraḥ', expected: true, vowel: 'u' },
  { word: 'ūrdhvaḥ', expected: true, vowel: 'ū' },
  { word: 'ṛṣiḥ', expected: true, vowel: 'ṛ' },
  { word: 'ṝtuḥ', expected: true, vowel: 'ṝ' },
  { word: 'ḷkāraḥ', expected: true, vowel: 'ḷ' },
  { word: 'ḹkāraḥ', expected: true, vowel: 'ḹ' },
  { word: 'indraḥ', expected: true, vowel: 'i' },
  { word: 'īkṣaṇaḥ', expected: true, vowel: 'ī' },
  { word: 'udakaḥ', expected: true, vowel: 'u' },
  { word: 'ūrjaḥ', expected: true, vowel: 'ū' },
  { word: 'ṛjuḥ', expected: true, vowel: 'ṛ' },
  { word: 'itaraḥ', expected: true, vowel: 'i' },
  { word: 'īryā', expected: true, vowel: 'ī' },
  { word: 'utsavaḥ', expected: true, vowel: 'u' },
  { word: 'ūhas', expected: true, vowel: 'ū' },
  { word: 'ṛtuḥ', expected: true, vowel: 'ṛ' },
  { word: 'icchā', expected: true, vowel: 'i' },
  { word: 'īpsā', expected: true, vowel: 'ī' },
  { word: 'ucyate', expected: true, vowel: 'u' },
  { word: 'ūṃ', expected: true, vowel: 'ū' },
  { word: 'ṛṇaḥ', expected: true, vowel: 'ṛ' },
  { word: 'indriyaḥ', expected: true, vowel: 'i' },
  { word: 'īṣṭaḥ', expected: true, vowel: 'ī' },

  // Words with non-'ik' vowels - should return false for isIkVowel
  { word: 'agniḥ', expected: false, vowel: 'a' },
  { word: 'āgamaḥ', expected: false, vowel: 'ā' },
  { word: 'ekaḥ', expected: false, vowel: 'e' },
  { word: 'oṣṭhaḥ', expected: false, vowel: 'o' },
  { word: 'aikyaḥ', expected: false, vowel: 'ai' },
  { word: 'auṣadhaḥ', expected: false, vowel: 'au' },
  { word: 'aśvaḥ', expected: false, vowel: 'a' },
  { word: 'ādityaḥ', expected: false, vowel: 'ā' },
  { word: 'ekādaśa', expected: false, vowel: 'e' },
  { word: 'ojas', expected: false, vowel: 'o' },
  { word: 'aiśvaryaḥ', expected: false, vowel: 'ai' },
  { word: 'aupāsanaḥ', expected: false, vowel: 'au' },
  { word: 'artha', expected: false, vowel: 'a' },
  { word: 'ālayaḥ', expected: false, vowel: 'ā' },
  { word: 'eva', expected: false, vowel: 'e' },
  { word: 'oma', expected: false, vowel: 'o' },
  { word: 'aiśānaḥ', expected: false, vowel: 'ai' },
  { word: 'aupanyāsaḥ', expected: false, vowel: 'au' },
  { word: 'akṣaḥ', expected: false, vowel: 'a' },
  { word: 'ākāśaḥ', expected: false, vowel: 'ā' },
  { word: 'etad', expected: false, vowel: 'e' },
  { word: 'oḍu', expected: false, vowel: 'o' },
  { word: 'aikatvaḥ', expected: false, vowel: 'ai' },
  { word: 'aumkāraḥ', expected: false, vowel: 'au' },
  { word: 'annaḥ', expected: false, vowel: 'a' }
];

export const devanagariTestCases = [
  // Words with 'ik' vowels - should return true for isIkVowel
  { word: 'इति', expected: true, vowel: 'इ' },
  { word: 'ईश', expected: true, vowel: 'ई' },
  { word: 'उपकरः', expected: true, vowel: 'उ' },
  { word: 'ऊर्ध्वः', expected: true, vowel: 'ऊ' },
  { word: 'ऋषिः', expected: true, vowel: 'ऋ' },
  { word: 'ॠतुः', expected: true, vowel: 'ॠ' },
  { word: 'ऌकारः', expected: true, vowel: 'ऌ' },
  { word: 'ॡकारः', expected: true, vowel: 'ॡ' },
  { word: 'इन्द्रः', expected: true, vowel: 'इ' },
  { word: 'ईक्षणः', expected: true, vowel: 'ई' },
  { word: 'उदकः', expected: true, vowel: 'उ' },
  { word: 'ऊर्जः', expected: true, vowel: 'ऊ' },
  { word: 'ऋजुः', expected: true, vowel: 'ऋ' },
  { word: 'इतरः', expected: true, vowel: 'इ' },
  { word: 'ईर्या', expected: true, vowel: 'ई' },
  { word: 'उत्सवः', expected: true, vowel: 'उ' },
  { word: 'ऊहस्', expected: true, vowel: 'ऊ' },
  { word: 'ऋतुः', expected: true, vowel: 'ऋ' },
  { word: 'इच्छा', expected: true, vowel: 'इ' },
  { word: 'ईप्सा', expected: true, vowel: 'ई' },
  { word: 'उच्यते', expected: true, vowel: 'उ' },
  { word: 'ऊँ', expected: true, vowel: 'ऊ' },
  { word: 'ऋणः', expected: true, vowel: 'ऋ' },
  { word: 'इन्द्रियः', expected: true, vowel: 'इ' },
  { word: 'ईष्टः', expected: true, vowel: 'ई' },

  // Words with non-'ik' vowels - should return false for isIkVowel
  { word: 'अग्निः', expected: false, vowel: 'अ' },
  { word: 'आगमः', expected: false, vowel: 'आ' },
  { word: 'एकः', expected: false, vowel: 'ए' },
  { word: 'ओष्ठः', expected: false, vowel: 'ओ' },
  { word: 'ऐक्यः', expected: false, vowel: 'ऐ' },
  { word: 'औषधः', expected: false, vowel: 'औ' },
  { word: 'अश्वः', expected: false, vowel: 'अ' },
  { word: 'आदित्यः', expected: false, vowel: 'आ' },
  { word: 'एकादश', expected: false, vowel: 'ए' },
  { word: 'ओजस्', expected: false, vowel: 'ओ' },
  { word: 'ऐश्वर्यः', expected: false, vowel: 'ऐ' },
  { word: 'औपासनः', expected: false, vowel: 'औ' },
  { word: 'अर्थ', expected: false, vowel: 'अ' },
  { word: 'आलयः', expected: false, vowel: 'आ' },
  { word: 'एव', expected: false, vowel: 'ए' },
  { word: 'ओम', expected: false, vowel: 'ओ' },
  { word: 'ऐशानः', expected: false, vowel: 'ऐ' },
  { word: 'औपन्यासः', expected: false, vowel: 'औ' },
  { word: 'अक्षः', expected: false, vowel: 'अ' },
  { word: 'आकाशः', expected: false, vowel: 'आ' },
  { word: 'एतद्', expected: false, vowel: 'ए' },
  { word: 'ओडु', expected: false, vowel: 'ओ' },
  { word: 'ऐकत्वः', expected: false, vowel: 'ऐ' },
  { word: 'औंकारः', expected: false, vowel: 'औ' },
  { word: 'अन्नः', expected: false, vowel: 'अ' }
];
