export const iastTestCases = [
  // Vṛddhi vowels - should return true
  { word: 'āgamaḥ', expected: true },
  { word: 'saikataḥ', expected: true },
  { word: 'nauḥ', expected: true },
  { word: 'auṣadham', expected: true },
  { word: 'mālikā', expected: true },
  { word: 'pāṭhaḥ', expected: true },
  { word: 'kāryam', expected: true },
  { word: 'daivam', expected: true },
  { word: 'gauravam', expected: true },
  { word: 'yauvanam', expected: true },
  { word: 'bhānuḥ', expected: true },
  { word: 'bālaḥ', expected: true },
  { word: 'pārvatī', expected: true },
  { word: 'jñānam', expected: true },
  { word: 'vaidyaḥ', expected: true },
  { word: 'mauna', expected: true },
  { word: 'śālā', expected: true },
  { word: 'sainikaḥ', expected: true },
  { word: 'kauśalam', expected: true },
  { word: 'rāmaḥ', expected: true },
  { word: 'kāmaḥ', expected: true },
  { word: 'brāhmaṇaḥ', expected: true },


  // Non-vṛddhi vowels - should return false
  { word: 'gajaḥ', expected: false },
  { word: 'giriḥ', expected: false },
  { word: 'guruḥ', expected: false },
  { word: 'devaḥ', expected: false },
  { word: 'lokaḥ', expected: false },
  { word: 'muniḥ', expected: false },
  { word: 'nadī', expected: false },
  { word: 'vṛkṣaḥ', expected: false },
  { word: 'phalam', expected: false },
  { word: 'siṃhaḥ', expected: false },
  { word: 'sūryaḥ', expected: false },
  { word: 'himaḥ', expected: false },
  { word: 'īśvaraḥ', expected: false },
  { word: 'ūṣaraḥ', expected: false },
  { word: 'ṛṣiḥ', expected: false },
  { word: 'ḷkāraḥ', expected: false },
  { word: 'ekaḥ', expected: false },
  { word: 'oṣṭhaḥ', expected: false },
  { word: 'kṛṣṇaḥ', expected: false },
  { word: 'govindaḥ', expected: false },
  { word: 'viṣṇuḥ', expected: false },
  { word: 'maheśaḥ', expected: false },
  { word: 'sureśaḥ', expected: false },
  { word: 'gaṇeśaḥ', expected: false },
  { word: 'dharmaḥ', expected: false },
  { word: 'arthaḥ', expected: false },
  { word: 'mokṣaḥ', expected: false },
  { word: 'kṣatriyaḥ', expected: false },
];

export const devanagariTestCases = [
    // Vṛddhi vowels - should return true
    { word: 'आगमः', expected: true },
    { word: 'सैकतः', expected: true },
    { word: 'नौः', expected: true },
    { word: 'औषधम्', expected: true },
    { word: 'मालिका', expected: true },
    { word: 'पाठः', expected: true },
    { word: 'कार्यम्', expected: true },
    { word: 'दैवम्', expected: true },
    { word: 'गौरवम्', expected: true },
    { word: 'यौवनम्', expected: true },
    { word: 'भानुः', expected: true },
    { word: 'बालः', expected: true },
    { word: 'पार्वती', expected: true },
    { word: 'ज्ञानम्', expected: true },
    { word: 'वैद्यः', expected: true },
    { word: 'मौन', expected: true },
    { word: 'शाला', expected: true },
    { word: 'सैनिकः', expected: true },
    { word: 'कौशलम्', expected: true },
    { word: 'रामः', expected: true },
    { word: 'कामः', expected: true },
    { word: 'ब्राह्मणः', expected: true },

    // Non-vṛddhi vowels - should return false
    { word: 'गजः', expected: false },
    { word: 'गिरिः', expected: false },
    { word: 'गुरुः', expected: false },
    { word: 'देवः', expected: false },
    { word: 'लोकः', expected: false },
    { word: 'मुनिः', expected: false },
    { word: 'नदी', expected: false },
    { word: 'वृक्षः', expected: false },
    { word: 'फलम्', expected: false },
    { word: 'सिंहः', expected: false },
    { word: 'सूर्यः', expected: false },
    { word: 'हिमः', expected: false },
    { word: 'ईश्वरः', expected: false },
    { word: 'ऊषरः', expected: false },
    { word: 'ऋषिः', expected: false },
    { word: 'ऌकारः', expected: false },
    { word: 'एकः', expected: false },
    { word: 'ओष्ठः', expected: false },
    { word: 'कृष्णः', expected: false },
    { word: 'गोविन्दः', expected: false },
    { word: 'विष्णुः', expected: false },
    { word: 'महेशः', expected: false },
    { word: 'सुरेशः', expected: false },
    { word: 'गणेशः', expected: false },
    { word: 'धर्मः', expected: false },
    { word: 'अर्थः', expected: false },
    { word: 'मोक्षः', expected: false },
    { word: 'क्षत्रियः', expected: false },
];