export const iastTestCases = [
  // Vṛddhi vowels - should return true
  { word: 'āgamaḥ', vowel: 'ā', expected: true },
  { word: 'saikataḥ', vowel: 'ai', expected: true },
  { word: 'nauḥ', vowel: 'au', expected: true },
  { word: 'auṣadham', vowel: 'au', expected: true },
  { word: 'mālikā', vowel: 'ā', expected: true },
  { word: 'pāṭhaḥ', vowel: 'ā', expected: true },
  { word: 'kāryam', vowel: 'ā', expected: true },
  { word: 'daivam', vowel: 'ai', expected: true },
  { word: 'gauravam', vowel: 'au', expected: true },
  { word: 'yauvanam', vowel: 'au', expected: true },
  { word: 'bhānuḥ', vowel: 'ā', expected: true },
  { word: 'bālaḥ', vowel: 'ā', expected: true },
  { word: 'pārvatī', vowel: 'ā', expected: true },
  { word: 'jñānam', vowel: 'ā', expected: true },
  { word: 'vaidyaḥ', vowel: 'ai', expected: true },
  { word: 'mauna', vowel: 'au', expected: true },
  { word: 'śālā', vowel: 'ā', expected: true },
  { word: 'sainikaḥ', vowel: 'ai', expected: true },
  { word: 'kauśalam', vowel: 'au', expected: true },
  { word: 'rāmaḥ', vowel: 'ā', expected: true },
  { word: 'kāmaḥ', vowel: 'ā', expected: true },
  { word: 'brāhmaṇaḥ', vowel: 'ā', expected: true },


  // Non-vṛddhi vowels - should return false
  { word: 'gajaḥ', vowel: 'a', expected: false },
  { word: 'giriḥ', vowel: 'i', expected: false },
  { word: 'guruḥ', vowel: 'u', expected: false },
  { word: 'devaḥ', vowel: 'e', expected: false },
  { word: 'lokaḥ', vowel: 'o', expected: false },
  { word: 'muniḥ', vowel: 'u', expected: false },
  { word: 'nadī', vowel: 'a', expected: false },
  { word: 'vṛkṣaḥ', vowel: 'ṛ', expected: false },
  { word: 'phalam', vowel: 'a', expected: false },
  { word: 'siṃhaḥ', vowel: 'i', expected: false },
  { word: 'sūryaḥ', vowel: 'ū', expected: false },
  { word: 'himaḥ', vowel: 'i', expected: false },
  { word: 'īśvaraḥ', vowel: 'ī', expected: false },
  { word: 'ūṣaraḥ', vowel: 'ū', expected: false },
  { word: 'ṛṣiḥ', vowel: 'ṛ', expected: false },
  { word: 'ḷkāraḥ', vowel: 'ḷ', expected: false },
  { word: 'ekaḥ', vowel: 'e', expected: false },
  { word: 'oṣṭhaḥ', vowel: 'o', expected: false },
  { word: 'kṛṣṇaḥ', vowel: 'ṛ', expected: false },
  { word: 'govindaḥ', vowel: 'o', expected: false },
  { word: 'viṣṇuḥ', vowel: 'i', expected: false },
  { word: 'maheśaḥ', vowel: 'a', expected: false },
  { word: 'sureśaḥ', vowel: 'u', expected: false },
  { word: 'gaṇeśaḥ', vowel: 'a', expected: false },
  { word: 'dharmaḥ', vowel: 'a', expected: false },
  { word: 'arthaḥ', vowel: 'a', expected: false },
  { word: 'mokṣaḥ', vowel: 'o', expected: false },
  { word: 'kṣatriyaḥ', vowel: 'a', expected: false },
];

export const devanagariTestCases = [
    // Vṛddhi vowels - should return true
    { word: 'आगमः', vowel: 'आ', expected: true },
    { word: 'सैकतः', vowel: 'ऐ', expected: true },
    { word: 'नौः', vowel: 'औ', expected: true },
    { word: 'औषधम्', vowel: 'औ', expected: true },
    { word: 'मालिका', vowel: 'आ', expected: true },
    { word: 'पाठः', vowel: 'आ', expected: true },
    { word: 'कार्यम्', vowel: 'आ', expected: true },
    { word: 'दैवम्', vowel: 'ऐ', expected: true },
    { word: 'गौरवम्', vowel: 'औ', expected: true },
    { word: 'यौवनम्', vowel: 'औ', expected: true },
    { word: 'भानुः', vowel: 'आ', expected: true },
    { word: 'बालः', vowel: 'आ', expected: true },
    { word: 'पार्वती', vowel: 'आ', expected: true },
    { word: 'ज्ञानम्', vowel: 'आ', expected: true },
    { word: 'वैद्यः', vowel: 'ऐ', expected: true },
    { word: 'मौन', vowel: 'औ', expected: true },
    { word: 'शाला', vowel: 'आ', expected: true },
    { word: 'सैनिकः', vowel: 'ऐ', expected: true },
    { word: 'कौशलम्', vowel: 'औ', expected: true },
    { word: 'रामः', vowel: 'आ', expected: true },
    { word: 'कामः', vowel: 'आ', expected: true },
    { word: 'ब्राह्मणः', vowel: 'आ', expected: true },

    // Non-vṛddhi vowels - should return false
    { word: 'गजः', vowel: 'अ', expected: false },
    { word: 'गिरिः', vowel: 'इ', expected: false },
    { word: 'गुरुः', vowel: 'उ', expected: false },
    { word: 'देवः', vowel: 'ए', expected: false },
    { word: 'लोकः', vowel: 'ओ', expected: false },
    { word: 'मुनिः', vowel: 'उ', expected: false },
    { word: 'नदी', vowel: 'अ', expected: false },
    { word: 'वृक्षः', vowel: 'ऋ', expected: false },
    { word: 'फलम्', vowel: 'अ', expected: false },
    { word: 'सिंहः', vowel: 'इ', expected: false },
    { word: 'सूर्यः', vowel: 'ऊ', expected: false },
    { word: 'हिमः', vowel: 'इ', expected: false },
    { word: 'ईश्वरः', vowel: 'ई', expected: false },
    { word: 'ऊषरः', vowel: 'ऊ', expected: false },
    { word: 'ऋषिः', vowel: 'ऋ', expected: false },
    { word: 'ऌकारः', vowel: 'ऌ', expected: false },
    { word: 'एकः', vowel: 'ए', expected: false },
    { word: 'ओष्ठः', vowel: 'ओ', expected: false },
    { word: 'कृष्णः', vowel: 'ऋ', expected: false },
    { word: 'गोविन्दः', vowel: 'ओ', expected: false },
    { word: 'विष्णुः', vowel: 'इ', expected: false },
    { word: 'महेशः', vowel: 'अ', expected: false },
    { word: 'सुरेशः', vowel: 'उ', expected: false },
    { word: 'गणेशः', vowel: 'अ', expected: false },
    { word: 'धर्मः', vowel: 'अ', expected: false },
    { word: 'अर्थः', vowel: 'अ', expected: false },
    { word: 'मोक्षः', vowel: 'ओ', expected: false },
    { word: 'क्षत्रियः', vowel: 'अ', expected: false },
];