const iastTestCases = [
  // Consonant-ending words (हलन्त)
  { word: 'vāk', expected: true, type: 'velar', meaning: 'speech', category: 'classical' },
  { word: 'jagat', expected: true, type: 'dental', meaning: 'world', category: 'classical' },
  { word: 'marut', expected: true, type: 'dental', meaning: 'wind god', category: 'vedic' },
  { word: 'vidyut', expected: true, type: 'dental', meaning: 'lightning', category: 'classical' },
  { word: 'samrāj', expected: true, type: 'palatal', meaning: 'emperor', category: 'classical' },
  { word: 'gup', expected: true, type: 'labial', meaning: 'guard', category: 'verb-root' },
  { word: 'triṣ', expected: true, type: 'sibilant', meaning: 'thrice', category: 'adverb' },
  { word: 'dhanuṣ', expected: true, type: 'sibilant', meaning: 'bow', category: 'classical' },
  { word: 'ahan', expected: true, type: 'dental', meaning: 'day', category: 'classical' },
  { word: 'pathin', expected: true, type: 'dental', meaning: 'path', category: 'classical' },
  { word: 'mahat', expected: true, type: 'dental', meaning: 'great', category: 'adjective' },
  { word: 'bhavat', expected: true, type: 'dental', meaning: 'you (formal)', category: 'pronoun' },
  { word: 'rājan', expected: true, type: 'dental', meaning: 'king', category: 'classical' },
  { word: 'ātman', expected: true, type: 'dental', meaning: 'self/soul', category: 'philosophy' },
  { word: 'vāc', expected: true, type: 'palatal', meaning: 'speech', category: 'classical' },
  { word: 'sarit', expected: true, type: 'dental', meaning: 'river', category: 'classical' },
  { word: 'āpad', expected: true, type: 'dental', meaning: 'calamity', category: 'classical' },
  { word: 'śarad', expected: true, type: 'dental', meaning: 'autumn', category: 'classical' },
  { word: 'diś', expected: true, type: 'sibilant', meaning: 'direction', category: 'classical' },
  { word: 'viś', expected: true, type: 'sibilant', meaning: 'settlement', category: 'classical' },
  { word: 'suhṛd', expected: true, type: 'dental', meaning: 'friend', category: 'classical' },
  { word: 'samit', expected: true, type: 'dental', meaning: 'fuel-stick', category: 'ritual' },
  { word: 'yakṛt', expected: true, type: 'dental', meaning: 'liver', category: 'anatomy' },
  { word: 'śakṛt', expected: true, type: 'dental', meaning: 'dung', category: 'classical' },
  { word: 'bhagavat', expected: true, type: 'dental', meaning: 'blessed one', category: 'religious' },
  { word: 'manas', expected: true, type: 'sibilant', meaning: 'mind', category: 'philosophy' },
  { word: 'yaśas', expected: true, type: 'sibilant', meaning: 'fame', category: 'classical' },
  { word: 'tejas', expected: true, type: 'sibilant', meaning: 'splendor', category: 'classical' },
  { word: 'payas', expected: true, type: 'sibilant', meaning: 'water/milk', category: 'classical' },
  { word: 'saras', expected: true, type: 'sibilant', meaning: 'lake', category: 'classical' },
  { word: 'rāmaḥ', expected: true, type: 'special', meaning: 'Rama (visarga)', category: 'epic' },
  { word: 'hariḥ', expected: true, type: 'special', meaning: 'Hari (visarga)', category: 'religious' },
  { word: 'guruḥ', expected: true, type: 'special', meaning: 'Guru (visarga)', category: 'religious' },
  { word: 'phalam', expected: true, type: 'labial', meaning: 'fruit (anusvara)', category: 'classical' },
  { word: 'vanam', expected: true, type: 'labial', meaning: 'forest (anusvara)', category: 'classical' },

  // Vowel-ending words (अजन्त)
  { word: 'rāma', expected: false, type: null, meaning: 'Rama', category: 'epic' },
  { word: 'hari', expected: false, type: null, meaning: 'Hari', category: 'religious' },
  { word: 'guru', expected: false, type: null, meaning: 'Guru', category: 'religious' },
  { word: 'pitṛ', expected: false, type: null, meaning: 'father', category: 'family' },
  { word: 'latā', expected: false, type: null, meaning: 'creeper', category: 'nature' },
  { word: 'nadī', expected: false, type: null, meaning: 'river', category: 'nature' },
  { word: 'vadhū', expected: false, type: null, meaning: 'bride', category: 'family' },
  { word: 'mati', expected: false, type: null, meaning: 'intellect', category: 'philosophy' },
  { word: 'phala', expected: false, type: null, meaning: 'fruit', category: 'nature' },
  { word: 'jñāna', expected: false, type: null, meaning: 'knowledge', category: 'philosophy' },
  { word: 'deva', expected: false, type: null, meaning: 'god', category: 'religious' },
  { word: 'sūrya', expected: false, type: null, meaning: 'sun', category: 'nature' },
  { word: 'candra', expected: false, type: null, meaning: 'moon', category: 'nature' },
  { word: 'yoga', expected: false, type: null, meaning: 'yoga', category: 'philosophy' },
];

const devanagariTestCases = [
  // Consonant-ending words (हलन्त)
  { word: 'वाक्', expected: true, type: 'velar', meaning: 'speech', category: 'classical' },
  { word: 'जगत्', expected: true, type: 'dental', meaning: 'world', category: 'classical' },
  { word: 'मरुत्', expected: true, type: 'dental', meaning: 'wind god', category: 'vedic' },
  { word: 'विद्युत्', expected: true, type: 'dental', meaning: 'lightning', category: 'classical' },
  { word: 'सम्राज्', expected: true, type: 'palatal', meaning: 'emperor', category: 'classical' },
  { word: 'गुप्', expected: true, type: 'labial', meaning: 'guard', category: 'verb-root' },
  { word: 'त्रिष्', expected: true, type: 'sibilant', meaning: 'thrice', category: 'adverb' },
  { word: 'धनुष्', expected: true, type: 'sibilant', meaning: 'bow', category: 'classical' },
  { word: 'अहन्', expected: true, type: 'dental', meaning: 'day', category: 'classical' },
  { word: 'पथिन्', expected: true, type: 'dental', meaning: 'path', category: 'classical' },
  { word: 'महत्', expected: true, type: 'dental', meaning: 'great', category: 'adjective' },
  { word: 'भवत्', expected: true, type: 'dental', meaning: 'you (formal)', category: 'pronoun' },
  { word: 'राजन्', expected: true, type: 'dental', meaning: 'king', category: 'classical' },
  { word: 'आत्मन्', expected: true, type: 'dental', meaning: 'self/soul', category: 'philosophy' },
  { word: 'वाच्', expected: true, type: 'palatal', meaning: 'speech', category: 'classical' },
  { word: 'सरित्', expected: true, type: 'dental', meaning: 'river', category: 'classical' },
  { word: 'आपद्', expected: true, type: 'dental', meaning: 'calamity', category: 'classical' },
  { word: 'शरद्', expected: true, type: 'dental', meaning: 'autumn', category: 'classical' },
  { word: 'दिश्', expected: true, type: 'sibilant', meaning: 'direction', category: 'classical' },
  { word: 'विश्', expected: true, type: 'sibilant', meaning: 'settlement', category: 'classical' },
  { word: 'सुहृद्', expected: true, type: 'dental', meaning: 'friend', category: 'classical' },
  { word: 'समित्', expected: true, type: 'dental', meaning: 'fuel-stick', category: 'ritual' },
  { word: 'यकृत्', expected: true, type: 'dental', meaning: 'liver', category: 'anatomy' },
  { word: 'शकृत्', expected: true, type: 'dental', meaning: 'dung', category: 'classical' },
  { word: 'भगवत्', expected: true, type: 'dental', meaning: 'blessed one', 'category': 'religious' },
  { word: 'मनस्', expected: true, type: 'sibilant', meaning: 'mind', category: 'philosophy' },
  { word: 'यशस्', expected: true, type: 'sibilant', meaning: 'fame', category: 'classical' },
  { word: 'तेजस्', expected: true, type: 'sibilant', meaning: 'splendor', category: 'classical' },
  { word: 'पयस्', expected: true, type: 'sibilant', meaning: 'water/milk', category: 'classical' },
  { word: 'सरस्', expected: true, type: 'sibilant', meaning: 'lake', category: 'classical' },
  { word: 'सूर्य', expected: false, type: null, meaning: 'sun', category: 'nature' },
  { word: 'चन्द्र', expected: false, type: null, meaning: 'moon', category: 'nature' },
  { word: 'रामः', expected: true, type: 'special', meaning: 'Rama (visarga)', category: 'epic' },
  { word: 'हरिः', expected: true, type: 'special', meaning: 'Hari (visarga)', category: 'religious' },
  { word: 'गुरुः', expected: true, type: 'special', meaning: 'Guru (visarga)', category: 'religious' },
  { word: 'फलम्', expected: true, type: 'labial', meaning: 'fruit (anusvara)', category: 'classical' },
  { word: 'वनम्', expected: true, type: 'labial', meaning: 'forest (anusvara)', category: 'classical' },

  // Vowel-ending words (अजन्त)
  { word: 'राम', expected: false, type: null, meaning: 'Rama', category: 'epic' },
  { word: 'हरि', expected: false, type: null, meaning: 'Hari', category: 'religious' },
  { word: 'गुरु', expected: false, type: null, meaning: 'Guru', category: 'religious' },
  { word: 'पितृ', expected: false, type: null, meaning: 'father', category: 'family' },
  { word: 'लता', expected: false, type: null, meaning: 'creeper', category: 'nature' },
  { word: 'नदी', expected: false, type: null, meaning: 'river', category: 'nature' },
  { word: 'वधू', expected: false, type: null, meaning: 'bride', category: 'family' },
  { word: 'मति', expected: false, type: null, meaning: 'intellect', category: 'philosophy' },
  { word: 'फल', expected: false, type: null, meaning: 'fruit', category: 'nature' },
  { word: 'ज्ञान', expected: false, type: null, meaning: 'knowledge', category: 'philosophy' },
  { word: 'देव', expected: false, type: null, meaning: 'god', category: 'religious' },
  { word: 'योग', expected: false, type: null, meaning: 'yoga', category: 'philosophy' },
];

export { iastTestCases, devanagariTestCases };
