export const iastTestCases = [
  // Guṇa vowels - should return true
  { word: 'agniḥ', expected: true },
  { word: 'ekaḥ', expected: true },
  { word: 'oṣṭhaḥ', expected: true },
  { word: 'aśvaḥ', expected: true },
  { word: 'ekādaśa', expected: true },
  { word: 'ojas', expected: true },
  { word: 'akṣaḥ', expected: true },
  { word: 'eva', expected: true },
  { word: 'oma', expected: true },
  { word: 'adhyakṣaḥ', expected: true },
  { word: 'etad', expected: true },
  { word: 'oḍu', expected: true },
  { word: 'annaḥ', expected: true },
  { word: 'eṣaḥ', expected: true },
  { word: 'okāraḥ', expected: true },
  { word: 'artha', expected: true },
  { word: 'edhate', expected: true },
  { word: 'oṅkāraḥ', expected: true },
  { word: 'ajñānaḥ', expected: true },
  { word: 'eva', expected: true },
  { word: 'oṣadhi', expected: true },
  { word: 'akāraḥ', expected: true },
  { word: 'ekatra', expected: true },
  { word: 'oja', expected: true },
  { word: 'antaḥ', expected: true },

  // Non-guṇa vowels - should return false  
  { word: 'īśvaraḥ', expected: false },
  { word: 'ūrdhvaḥ', expected: false },
  { word: 'ṛṣiḥ', expected: false },
  { word: 'ḷkāraḥ', expected: false },
  { word: 'āgamaḥ', expected: false },
  { word: 'aiśvaryaḥ', expected: false },
  { word: 'auṣadhaḥ', expected: false },
  { word: 'itaraḥ', expected: false },
  { word: 'udakaḥ', expected: false },
  { word: 'īkṣaṇaḥ', expected: false },
  { word: 'ūrjaḥ', expected: false },
  { word: 'ṛtuḥ', expected: false },
  { word: 'ādaraḥ', expected: false },
  { word: 'aikyaḥ', expected: false },
  { word: 'aupāsanaḥ', expected: false },
  { word: 'indraḥ', expected: false },
  { word: 'upakaraḥ', expected: false },
  { word: 'īryā', expected: false },
  { word: 'ūhas', expected: false },
  { word: 'ṛjuḥ', expected: false },
  { word: 'āyuḥ', expected: false },
  { word: 'aiśānaḥ', expected: false },
  { word: 'aupanyāsaḥ', expected: false },
  { word: 'icchā', expected: false },
  { word: 'ucyate', expected: false }
];

export const devanagariTestCases = [
  // Guṇa vowels - should return true
  { word: 'अग्निः', expected: true },
  { word: 'एकः', expected: true },
  { word: 'ओष्ठः', expected: true },
  { word: 'अश्वः', expected: true },
  { word: 'एकादश', expected: true },
  { word: 'ओजस्', expected: true },
  { word: 'अक्षः', expected: true },
  { word: 'एव', expected: true },
  { word: 'ओम', expected: true },
  { word: 'अध्यक्षः', expected: true },
  { word: 'एतद्', expected: true },
  { word: 'ओडु', expected: true },
  { word: 'अन्नः', expected: true },
  { word: 'एषः', expected: true },
  { word: 'ओकारः', expected: true },
  { word: 'अर्थ', expected: true },
  { word: 'एधते', expected: true },
  { word: 'ओङ्कारः', expected: true },
  { word: 'अज्ञानः', expected: true },
  { word: 'एव', expected: true },
  { word: 'ओषधि', expected: true },
  { word: 'अकारः', expected: true },
  { word: 'एकत्र', expected: true },
  { word: 'ओज', expected: true },
  { word: 'अन्तः', expected: true },

  // Non-guṇa vowels - should return false
  { word: 'ईश्वरः', expected: false },
  { word: 'ऊर्ध्वः', expected: false },
  { word: 'ऋषिः', expected: false },
  { word: 'ऌकारः', expected: false },
  { word: 'आगमः', expected: false },
  { word: 'ऐश्वर्यः', expected: false },
  { word: 'औषधः', expected: false },
  { word: 'इतरः', expected: false },
  { word: 'उदकः', expected: false },
  { word: 'ईक्षणः', expected: false },
  { word: 'ऊर्जः', expected: false },
  { word: 'ऋतुः', expected: false },
  { word: 'आदरः', expected: false },
  { word: 'ऐक्यः', expected: false },
  { word: 'औपासनः', expected: false },
  { word: 'इन्द्रः', expected: false },
  { word: 'उपकरः', expected: false },
  { word: 'ईर्या', expected: false },
  { word: 'ऊहस्', expected: false },
  { word: 'ऋजुः', expected: false },
  { word: 'आयुः', expected: false },
  { word: 'ऐशानः', expected: false },
  { word: 'औपन्यासः', expected: false },
  { word: 'इच्छा', expected: false },
  { word: 'उच्यते', expected: false }
];
